name: "Publish Documentation"

on:
  workflow_call:
    secrets:
      BOT_SK:
        required: true
      BOT_ID:
        required: true

  workflow_dispatch:

jobs:
  publish-docs-to-pages:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      # --- BUILD STEPS (Previously in Composite Action) ---
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Npm install
        run: npm ci --ignore-scripts

      - name: Build doc (Run typedoc)
        run: npm run generate:code-docs
      # ----------------------------------------------------

      # --- DEPLOYMENT STEPS (Original in this file) ---
      - name: Generate bot token for deployment
        uses: actions/create-github-app-token@v1
        id: app_token
        with:
          app_id: ${{secrets.BOT_ID}}
          private_key: ${{secrets.BOT_SK}}

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_html # Ensure this path is correct for your build output

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ steps.app_token.outputs.token }}
